#define DYNAMIC_MACRO_NO_NESTING
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define LEADER_NO_TIMEOUT
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define COMBO_MUST_HOLD_MODS
#define NO_MUSIC_MODE
#define COMBO_TERM 25
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 8
#define MOUSEKEY_MAX_SPEED 2
